"""
Simple Self-Distillation (SSD) Fine-Tuning Script.
Trains RoMa and SEA-RAFT models on pseudo-labels generated by `extract_pseudo_labels.py`.

RoMa: Freeze DINOv3 backbone, train matcher + refiners against teacher correspondences.
SEA-RAFT: Uses built-in NF loss against teacher flow pseudo-labels.

Metrics logged to JSONL + optional TensorBoard for inspection and Optuna tuning.
"""

import argparse
import glob
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent))

from align.models import get_torch_device

# Optional TensorBoard
_tb_available = False
try:
    from torch.utils.tensorboard import SummaryWriter
    _tb_available = True
except ImportError:
    pass


# ---------------------------------------------------------------------------
# Metrics Logger
# ---------------------------------------------------------------------------

class MetricsLogger:
    """Writes JSONL metrics + optional TensorBoard scalars."""

    def __init__(self, run_dir, model_name, use_tb=True):
        os.makedirs(run_dir, exist_ok=True)
        self.jsonl_path = os.path.join(run_dir, f"metrics_{model_name}.jsonl")
        self.jsonl_file = open(self.jsonl_path, "a")
        self.model_name = model_name
        self.global_step = 0

        self.tb_writer = None
        if use_tb and _tb_available:
            tb_dir = os.path.join(run_dir, "tb", model_name)
            self.tb_writer = SummaryWriter(log_dir=tb_dir)

    def log(self, metrics: dict):
        metrics["model"] = self.model_name
        metrics["step"] = self.global_step
        self.jsonl_file.write(json.dumps(metrics) + "\n")
        self.jsonl_file.flush()

        if self.tb_writer:
            for k, v in metrics.items():
                if isinstance(v, (int, float)) and k not in ("step", "epoch", "batch"):
                    self.tb_writer.add_scalar(k, v, self.global_step)

        self.global_step += 1

    def log_config(self, config: dict):
        config["type"] = "run_config"
        config["model"] = self.model_name
        config["timestamp"] = datetime.now(timezone.utc).isoformat()
        self.jsonl_file.write(json.dumps(config) + "\n")
        self.jsonl_file.flush()

    def close(self):
        self.jsonl_file.close()
        if self.tb_writer:
            self.tb_writer.close()


def _split_dataset(train_dataset, eval_dataset, train_frac=0.8, val_frac=0.1, seed=42):
    """Split into train (augmented) / val (clean) / test (clean).

    Args:
        train_dataset: dataset with augment=True (used for train split)
        eval_dataset: dataset with augment=False (used for val/test splits)
    """
    from torch.utils.data import Subset
    n = len(train_dataset)
    assert len(eval_dataset) == n
    indices = list(range(n))
    rng = np.random.RandomState(seed)
    rng.shuffle(indices)
    n_train = int(n * train_frac)
    n_val = int(n * val_frac)
    train_idx = indices[:n_train]
    val_idx = indices[n_train:n_train + n_val]
    test_idx = indices[n_train + n_val:]
    return Subset(train_dataset, train_idx), Subset(eval_dataset, val_idx), Subset(eval_dataset, test_idx)


def _save_training_checkpoint(path, model, optimizer, scheduler, epoch, best_val_loss, patience_counter):
    torch.save({
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'epoch': epoch,
        'best_val_loss': best_val_loss,
        'patience_counter': patience_counter,
    }, path)


def _load_training_checkpoint(path, model, optimizer, scheduler, device):
    ckpt = torch.load(path, map_location=device, weights_only=False)
    model.load_state_dict(ckpt['model_state_dict'])
    optimizer.load_state_dict(ckpt['optimizer_state_dict'])
    scheduler.load_state_dict(ckpt['scheduler_state_dict'])
    return ckpt['epoch'], ckpt['best_val_loss'], ckpt['patience_counter']


def _photometric_augment(img, rng):
    """Apply random photometric jitter to a uint8 image (H, W, C) or (H, W).

    Applies brightness, contrast, gamma, and Gaussian noise independently
    to simulate cross-sensor radiometric differences.
    """
    img = img.astype(np.float32)

    # Brightness: +/- 20%
    brightness = rng.uniform(0.8, 1.2)
    img = img * brightness

    # Contrast: +/- 20% around mean
    mean = img.mean()
    contrast = rng.uniform(0.8, 1.2)
    img = (img - mean) * contrast + mean

    # Gamma: 0.7 - 1.4
    gamma = rng.uniform(0.7, 1.4)
    img = np.clip(img, 0, 255)
    img = 255.0 * (img / 255.0) ** gamma

    # Gaussian noise: sigma 3-12
    sigma = rng.uniform(3, 12)
    noise = rng.normal(0, sigma, img.shape).astype(np.float32)
    img = img + noise

    return np.clip(img, 0, 255).astype(np.uint8)


def _random_hflip(ref, src, m, flow, rng):
    """Random horizontal flip with label adjustment.

    Args:
        ref, src: images (H, W, C) or (H, W)
        m: RoMa correspondences (N, 4) in [-1, 1] or None
        flow: optical flow (H, W, 2) or None
        rng: numpy RandomState
    Returns:
        Flipped (ref, src, m, flow) or originals.
    """
    if rng.random() < 0.5:
        return ref, src, m, flow

    ref = np.ascontiguousarray(ref[:, ::-1])
    src = np.ascontiguousarray(src[:, ::-1])

    if m is not None:
        m = m.clone()
        m[:, 0] = -m[:, 0]  # flip x coords in A
        m[:, 2] = -m[:, 2]  # flip x coords in B

    if flow is not None:
        flow = flow[:, ::-1].copy()
        flow[:, :, 0] = -flow[:, :, 0]  # flip horizontal flow component

    return ref, src, m, flow


def _compute_frozen_features(model, refs, srcs, device):
    """Compute frozen backbone + mv_vit features on-the-fly for a batch.

    Returns (f_A, f_B, f_mv_A, f_mv_B, img_A_lr, img_B_lr) on device.
    """
    with torch.no_grad():
        img_A_lr = F.interpolate(refs, size=(model.H_lr, model.W_lr),
                                 mode="bicubic", align_corners=False, antialias=True)
        img_B_lr = F.interpolate(srcs, size=(model.H_lr, model.W_lr),
                                 mode="bicubic", align_corners=False, antialias=True)
        f_A = model.f(img_A_lr)
        f_B = model.f(img_B_lr)

        f_A_cat = torch.cat(f_A, dim=-1)
        f_B_cat = torch.cat(f_B, dim=-1)
        with torch.autocast(device, torch.bfloat16, enabled=True):
            f_mv_AB = model.matcher.mv_vit(
                torch.stack((f_A_cat, f_B_cat), dim=1)
            )["x_norm_patchtokens"]
            B_sz = f_A_cat.shape[0]
            H_A, W_A = f_A_cat.shape[1], f_A_cat.shape[2]
            f_mv_AB = f_mv_AB.reshape(B_sz, 2, H_A, W_A, model.matcher.cfg.dim)

        f_mv_A = f_mv_AB[:, 0].float()
        f_mv_B = f_mv_AB[:, 1].float()

    return f_A, f_B, f_mv_A, f_mv_B, img_A_lr, img_B_lr


def _get_mem_mb(device):
    if "mps" in str(device):
        try:
            return torch.mps.current_allocated_memory() / 1e6
        except Exception:
            return 0
    elif "cuda" in str(device):
        return torch.cuda.memory_allocated() / 1e6
    return 0


# ---------------------------------------------------------------------------
# RoMa SSD
# ---------------------------------------------------------------------------

class RomaSSDDataset(Dataset):
    """Loads pseudo-label .pt files + corresponding image pairs for RoMa SSD."""

    def __init__(self, label_dir, pairs_dir, roma_size=800, augment=True):
        self.roma_size = roma_size
        self.augment = augment
        self.label_files = sorted(glob.glob(os.path.join(label_dir, "roma_raw_*.pt")))
        self.pairs_dir = pairs_dir
        valid = []
        for lf in self.label_files:
            pair_id = self._extract_pair_id(lf)
            ref_path = os.path.join(pairs_dir, f"{pair_id}_ref.png")
            src_path = os.path.join(pairs_dir, f"{pair_id}_src_perturbed.png")
            if os.path.exists(ref_path) and os.path.exists(src_path):
                valid.append(lf)
        self.label_files = valid

    def _extract_pair_id(self, label_path):
        basename = os.path.basename(label_path)
        parts = basename.replace("roma_raw_", "").replace(".pt", "")
        idx = parts.rfind("_")
        return parts[:idx]

    def __len__(self):
        return len(self.label_files)

    def __getitem__(self, idx):
        label_path = self.label_files[idx]
        pair_id = self._extract_pair_id(label_path)

        label = torch.load(label_path, map_location='cpu', weights_only=False)
        m = torch.as_tensor(label['m'], dtype=torch.float32)
        c = torch.as_tensor(label['c'], dtype=torch.float32)

        ref_path = os.path.join(self.pairs_dir, f"{pair_id}_ref.png")
        src_path = os.path.join(self.pairs_dir, f"{pair_id}_src_perturbed.png")
        ref = cv2.imread(ref_path)
        src = cv2.imread(src_path)

        if self.augment:
            rng = np.random.RandomState()
            ref, src, m, _ = _random_hflip(ref, src, m, None, rng)
            ref = _photometric_augment(ref, np.random.RandomState())
            src = _photometric_augment(src, np.random.RandomState())

        ref = cv2.resize(ref, (self.roma_size, self.roma_size), interpolation=cv2.INTER_AREA)
        src = cv2.resize(src, (self.roma_size, self.roma_size), interpolation=cv2.INTER_AREA)

        ref_t = torch.from_numpy(ref).permute(2, 0, 1).float() / 255.0
        src_t = torch.from_numpy(src).permute(2, 0, 1).float() / 255.0

        return ref_t, src_t, m, c



def roma_ssd_collate(batch):
    refs = torch.stack([b[0] for b in batch])
    srcs = torch.stack([b[1] for b in batch])
    ms = [b[2] for b in batch]
    cs = [b[3] for b in batch]
    return refs, srcs, ms, cs


def _eval_roma(model, loader, device, conf_weight):
    """Evaluate RoMa on a raw-image dataloader without gradients. Returns avg loss."""
    model.eval()
    total_loss = 0.0
    n = 0
    with torch.no_grad():
        for refs, srcs, ms_list, cs_list in loader:
            refs = refs.to(device)
            srcs = srcs.to(device)
            f_A, f_B, f_mv_A, f_mv_B, img_A_lr, img_B_lr = _compute_frozen_features(
                model, refs, srcs, device)
            B_sz = f_mv_A.shape[0]

            f_A_cat = torch.cat(f_A, dim=-1)
            H_A, W_A = f_A_cat.shape[1], f_A_cat.shape[2]
            from align.romav2.matcher import _compute_match_embeddings, _compute_head_preds
            from align.romav2.geometry import get_normalized_grid
            x = get_normalized_grid(B_sz, H_A, W_A)
            x_emb = nn.functional.linear(
                x.reshape(B_sz, H_A * W_A, 2),
                model.matcher.scale * model.matcher.omega
            ).reshape(B_sz, H_A, W_A, -1)
            pos_emb_grid = torch.cat((x_emb.sin(), x_emb.cos()), dim=-1)

            attn_AB_logits, attn_AB, match_emb_AB = _compute_match_embeddings(
                f_A=f_mv_A, f_B=f_mv_B, pos_emb_grid=pos_emb_grid,
                temp=model.matcher.temp, B=B_sz,
                H_A=H_A, W_A=W_A, H_B=H_A, W_B=W_A,
            )
            warp_AB, confidence_AB = _compute_head_preds(
                f_list_A=f_A, match_emb_AB=match_emb_AB, f_mv_A=f_mv_A,
                img_A=img_A_lr, img_B=img_B_lr, head=model.matcher.head,
            )

            loss = torch.tensor(0.0, device=device)
            for i in range(B_sz):
                m_target = ms_list[i].to(device)
                c_target = cs_list[i].to(device)
                if len(m_target) == 0:
                    continue
                warp_i = warp_AB[i]
                H_w, W_w = warp_i.shape[:2]
                px = ((m_target[:, 0] + 1) * 0.5 * (W_w - 1)).clamp(0, W_w - 1).long()
                py = ((m_target[:, 1] + 1) * 0.5 * (H_w - 1)).clamp(0, H_w - 1).long()
                pred_warp = warp_i[py, px].contiguous()
                target_warp = m_target[:, 2:].contiguous()
                warp_loss = F.smooth_l1_loss(pred_warp, target_warp)
                pred_conf = confidence_AB[i][py, px, 0]
                conf_loss = F.mse_loss(pred_conf, c_target)
                loss = loss + warp_loss + conf_weight * conf_loss
            total_loss += loss.item() / max(B_sz, 1)
            n += 1
    model.train()
    for m_mod in model.f.modules():
        if isinstance(m_mod, (nn.BatchNorm2d, nn.LayerNorm)):
            m_mod.eval()
    return total_loss / max(n, 1)


def train_roma_ssd(data_dir, pairs_dir, device, epochs=3, lr=1e-5, batch_size=1,
                   weight_decay=1e-4, conf_weight=0.5, grad_clip=5.0, grad_accum=1,
                   val_every=200, early_stop_patience=3, min_delta=0.001,
                   resume=False, run_dir=None, log_every=10, use_tb=True, trial=None):
    """Train RoMa via SSD. Returns best val_loss."""
    print("Starting RoMa Simple Self-Distillation...", flush=True)
    torch.set_float32_matmul_precision("highest")

    train_full = RomaSSDDataset(data_dir, pairs_dir, augment=True)
    eval_full = RomaSSDDataset(data_dir, pairs_dir, augment=False)
    if len(train_full) == 0:
        print("No RoMa training data found!")
        return float('inf')

    train_ds, val_ds, test_ds = _split_dataset(train_full, eval_full)
    print(f"  {len(train_full)} total -> train={len(train_ds)} val={len(val_ds)} test={len(test_ds)}", flush=True)

    # Load model
    from align.romav2 import RoMaV2
    from align.romav2.device import set_device
    set_device(device)
    print(f"  Loading RoMa model...", flush=True)
    cfg = RoMaV2.Cfg(setting="fast", compile=False)
    model = RoMaV2(cfg)
    model.apply_setting("satast")
    print(f"  RoMa model loaded", flush=True)

    # Freeze heavy pretrained components
    for param in model.f.parameters():
        param.requires_grad = False
    for param in model.matcher.mv_vit.parameters():
        param.requires_grad = False

    # Use raw-image dataloaders — frozen features computed on-the-fly per batch
    # to avoid ~450GB RAM cache (90MB/pair × 5k pairs)
    loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                        num_workers=2, persistent_workers=True,
                        collate_fn=roma_ssd_collate)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False,
                            num_workers=0, collate_fn=roma_ssd_collate)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False,
                             num_workers=0, collate_fn=roma_ssd_collate)

    trainable = [p for p in model.parameters() if p.requires_grad]
    n_trainable = sum(p.numel() for p in trainable)
    n_frozen = sum(p.numel() for p in model.f.parameters())
    print(f"  Trainable: {n_trainable:,} params (frozen backbone: {n_frozen:,})", flush=True)

    optimizer = optim.AdamW(trainable, lr=lr, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs * len(loader))

    # Logger
    logger = None
    if run_dir:
        logger = MetricsLogger(run_dir, "roma", use_tb=use_tb)
        logger.log_config({
            "lr": lr, "weight_decay": weight_decay, "conf_weight": conf_weight,
            "epochs": epochs, "batch_size": batch_size,
            "train_size": len(train_ds), "val_size": len(val_ds), "test_size": len(test_ds),
            "device": str(device), "trainable_params": n_trainable,
            "frozen_params": n_frozen,
        })

    model.train()
    for m in model.f.modules():
        if isinstance(m, (nn.BatchNorm2d, nn.LayerNorm)):
            m.eval()

    best_val_loss = float('inf')
    patience_counter = 0
    start_epoch = 0
    weights_path = 'align/weights/roma_ssd.pth'
    ckpt_path = 'align/weights/roma_ssd_training.pt'

    if resume and os.path.exists(ckpt_path):
        start_epoch, best_val_loss, patience_counter = _load_training_checkpoint(
            ckpt_path, model, optimizer, scheduler, device)
        start_epoch += 1  # resume from next epoch
        print(f"  Resumed from epoch {start_epoch}, best_val={best_val_loss:.5f}", flush=True)

    for epoch in range(start_epoch, epochs):
        total_loss = 0.0
        total_warp_loss = 0.0
        total_conf_loss = 0.0
        n_batches = 0
        epoch_t0 = time.time()

        for refs, srcs, ms_list, cs_list in loader:
            batch_t0 = time.time()
            refs = refs.to(device)
            srcs = srcs.to(device)
            f_A, f_B, f_mv_A, f_mv_B, img_A_lr, img_B_lr = _compute_frozen_features(
                model, refs, srcs, device)
            B_sz = f_mv_A.shape[0]

            # Trainable part of matcher: attention + head (skip frozen backbone + mv_vit)
            f_A_cat = torch.cat(f_A, dim=-1)
            H_A, W_A = f_A_cat.shape[1], f_A_cat.shape[2]
            H_B, W_B = H_A, W_A
            from align.romav2.geometry import get_normalized_grid
            x = get_normalized_grid(B_sz, H_A, W_A)
            x_emb = nn.functional.linear(
                x.reshape(B_sz, H_B * W_B, 2),
                model.matcher.scale * model.matcher.omega
            ).reshape(B_sz, H_B, W_B, -1)
            pos_emb_grid = torch.cat((x_emb.sin(), x_emb.cos()), dim=-1)

            from align.romav2.matcher import _compute_match_embeddings, _compute_head_preds
            attn_AB_logits, attn_AB, match_emb_AB = _compute_match_embeddings(
                f_A=f_mv_A, f_B=f_mv_B, pos_emb_grid=pos_emb_grid,
                temp=model.matcher.temp, B=B_sz,
                H_A=H_A, W_A=W_A, H_B=H_B, W_B=W_B,
            )
            warp_AB, confidence_AB = _compute_head_preds(
                f_list_A=f_A, match_emb_AB=match_emb_AB, f_mv_A=f_mv_A,
                img_A=img_A_lr, img_B=img_B_lr, head=model.matcher.head,
            )

            loss = torch.tensor(0.0, device=device)
            batch_warp = 0.0
            batch_conf = 0.0
            for i in range(B_sz):
                m_target = ms_list[i].to(device)
                c_target = cs_list[i].to(device)

                if len(m_target) == 0:
                    continue

                query_coords = m_target[:, :2]
                target_warp = m_target[:, 2:]

                warp_i = warp_AB[i]
                H_w, W_w = warp_i.shape[:2]
                px = ((query_coords[:, 0] + 1) * 0.5 * (W_w - 1)).clamp(0, W_w - 1).long()
                py = ((query_coords[:, 1] + 1) * 0.5 * (H_w - 1)).clamp(0, H_w - 1).long()
                pred_warp = warp_i[py, px].contiguous()
                target_warp = target_warp.contiguous()

                warp_loss = F.smooth_l1_loss(pred_warp, target_warp)

                conf_i = confidence_AB[i]
                pred_conf = conf_i[py, px, 0]
                conf_loss = F.mse_loss(pred_conf, c_target)

                loss = loss + warp_loss + conf_weight * conf_loss
                batch_warp += warp_loss.item()
                batch_conf += conf_loss.item()

            loss = loss / max(B_sz, 1)

            # Scale loss for gradient accumulation
            (loss / grad_accum).backward()

            loss_val = loss.item()
            total_loss += loss_val
            total_warp_loss += batch_warp / max(refs.shape[0], 1)
            total_conf_loss += batch_conf / max(refs.shape[0], 1)
            n_batches += 1

            # Step optimizer every grad_accum batches
            if n_batches % grad_accum == 0:
                grad_norm = torch.nn.utils.clip_grad_norm_(trainable, grad_clip).item()
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()
            else:
                grad_norm = 0.0
            batch_time = time.time() - batch_t0

            if n_batches % log_every == 0:
                cur_lr = scheduler.get_last_lr()[0]
                mem = _get_mem_mb(device)
                msg = (f"    [{n_batches}/{len(loader)}] loss={loss_val:.5f} "
                       f"warp={batch_warp:.5f} conf={batch_conf:.5f} "
                       f"grad={grad_norm:.3f} lr={cur_lr:.2e} "
                       f"{batch_time:.2f}s {mem:.0f}MB")
                print(msg, flush=True)

                if logger:
                    logger.log({
                        "type": "batch", "epoch": epoch, "batch": n_batches,
                        "loss": loss_val,
                        "warp_loss": batch_warp / max(refs.shape[0], 1),
                        "conf_loss": batch_conf / max(refs.shape[0], 1),
                        "grad_norm": grad_norm,
                        "lr": cur_lr,
                        "batch_time_s": batch_time,
                        "mem_mb": mem,
                    })

            # Intra-epoch val check
            if val_every and n_batches % val_every == 0:
                val_loss = _eval_roma(model, val_loader, device, conf_weight)
                improved = val_loss < best_val_loss - min_delta
                if improved:
                    best_val_loss = val_loss
                    patience_counter = 0
                    os.makedirs('align/weights', exist_ok=True)
                    torch.save(model.state_dict(), weights_path)
                    print(f"    VAL [{n_batches}] val={val_loss:.5f} [best, saved]", flush=True)
                else:
                    patience_counter += 1
                    print(f"    VAL [{n_batches}] val={val_loss:.5f} "
                          f"[no improvement {patience_counter}/{early_stop_patience}]", flush=True)

                if logger:
                    logger.log({
                        "type": "val_check", "epoch": epoch, "batch": n_batches,
                        "val_loss": val_loss, "best_val_loss": best_val_loss,
                    })

                if trial is not None:
                    trial.report(val_loss, epoch * len(loader) + n_batches)

                if early_stop_patience and patience_counter >= early_stop_patience:
                    print(f"    Early stopping at epoch {epoch+1} batch {n_batches}", flush=True)
                    break

        # Check if inner loop broke for early stopping
        if early_stop_patience and patience_counter >= early_stop_patience:
            break

        # End-of-epoch val check (only if not already checked recently)
        epoch_time = time.time() - epoch_t0
        avg_loss = total_loss / max(n_batches, 1)
        avg_warp = total_warp_loss / max(n_batches, 1)
        avg_conf = total_conf_loss / max(n_batches, 1)

        if not val_every or n_batches % val_every != 0:
            val_loss = _eval_roma(model, val_loader, device, conf_weight)
            improved = val_loss < best_val_loss - min_delta
            if improved:
                best_val_loss = val_loss
                patience_counter = 0
                os.makedirs('align/weights', exist_ok=True)
                torch.save(model.state_dict(), weights_path)

        print(f"  Epoch {epoch+1}/{epochs} — train={avg_loss:.5f} val={val_loss:.5f} "
              f"best={best_val_loss:.5f} warp={avg_warp:.5f} conf={avg_conf:.5f} "
              f"({epoch_time:.0f}s)", flush=True)

        if logger:
            logger.log({
                "type": "epoch_summary", "epoch": epoch,
                "train_loss": avg_loss, "val_loss": val_loss,
                "best_val_loss": best_val_loss,
                "avg_warp_loss": avg_warp, "avg_conf_loss": avg_conf,
                "epoch_time_s": epoch_time,
            })

        # Save training checkpoint for resume
        os.makedirs('align/weights', exist_ok=True)
        _save_training_checkpoint(ckpt_path, model, optimizer, scheduler,
                                  epoch, best_val_loss, patience_counter)
        print(f"  Training checkpoint saved (resumable)", flush=True)

    # Reload best weights for test eval
    if os.path.exists(weights_path):
        model.load_state_dict(torch.load(weights_path, map_location=device))

    test_loss = _eval_roma(model, test_loader, device, conf_weight)
    print(f"  Test loss: {test_loss:.5f} (best val: {best_val_loss:.5f})", flush=True)
    if logger:
        logger.log({"type": "test", "test_loss": test_loss, "best_val_loss": best_val_loss})
    print(f"  Weights at {weights_path}", flush=True)

    if logger:
        logger.close()

    del model, optimizer
    if "mps" in str(device):
        torch.mps.empty_cache()
    elif "cuda" in str(device):
        torch.cuda.empty_cache()

    return best_val_loss


# ---------------------------------------------------------------------------
# SEA-RAFT SSD
# ---------------------------------------------------------------------------

class SEARAFTSSDDataset(Dataset):
    """Loads SEA-RAFT pseudo-label flow/uncertainty + corresponding image pairs."""

    def __init__(self, label_dir, pairs_dir, crop_size=512, augment=True):
        self.crop_size = crop_size
        self.augment = augment
        self.pairs_dir = pairs_dir
        self.label_files = sorted(glob.glob(os.path.join(label_dir, "searaft_raw_*.pt")))
        valid = []
        for lf in self.label_files:
            pair_id = self._extract_pair_id(lf)
            ref_path = os.path.join(pairs_dir, f"{pair_id}_ref.png")
            src_path = os.path.join(pairs_dir, f"{pair_id}_src_perturbed.png")
            if os.path.exists(ref_path) and os.path.exists(src_path):
                valid.append(lf)
        self.label_files = valid

    def _extract_pair_id(self, label_path):
        return os.path.basename(label_path).replace("searaft_raw_", "").replace(".pt", "")

    def __len__(self):
        return len(self.label_files)

    def __getitem__(self, idx):
        label_path = self.label_files[idx]
        pair_id = self._extract_pair_id(label_path)

        label = torch.load(label_path, map_location='cpu', weights_only=False)
        flow_gt = torch.as_tensor(label['flow_fwd'], dtype=torch.float32)
        uncertainty = torch.as_tensor(label['uncertainty'], dtype=torch.float32)

        ref_path = os.path.join(self.pairs_dir, f"{pair_id}_ref.png")
        src_path = os.path.join(self.pairs_dir, f"{pair_id}_src_perturbed.png")
        ref = cv2.imread(ref_path, cv2.IMREAD_GRAYSCALE)
        src = cv2.imread(src_path, cv2.IMREAD_GRAYSCALE)

        # Random crop
        H, W = ref.shape
        cs = min(self.crop_size, H, W)
        y0 = np.random.randint(0, H - cs + 1) if H > cs else 0
        x0 = np.random.randint(0, W - cs + 1) if W > cs else 0

        ref = ref[y0:y0+cs, x0:x0+cs]
        src = src[y0:y0+cs, x0:x0+cs]
        flow_gt_np = flow_gt.numpy()[y0:y0+cs, x0:x0+cs]

        if self.augment:
            rng = np.random.RandomState()
            ref, src, _, flow_gt_np = _random_hflip(ref, src, None, flow_gt_np, rng)
            ref = _photometric_augment(ref, np.random.RandomState())
            src = _photometric_augment(src, np.random.RandomState())

        ref_t = torch.from_numpy(np.stack([ref]*3, axis=0)).float()
        src_t = torch.from_numpy(np.stack([src]*3, axis=0)).float()
        flow_gt = torch.from_numpy(flow_gt_np.copy()).permute(2, 0, 1).float()

        return ref_t, src_t, flow_gt


def _eval_searaft(model, loader, device, gamma):
    """Evaluate SEA-RAFT on a dataloader without gradients. Returns avg loss."""
    model.eval()
    total_loss = 0.0
    n = 0
    with torch.no_grad():
        for refs, srcs, flow_gts in loader:
            refs = refs.to(device)
            srcs = srcs.to(device)
            flow_gts = flow_gts.to(device)
            output = model(refs, srcs, iters=12, flow_gt=flow_gts, test_mode=False)
            nf_preds = output['nf']
            n_iters = len(nf_preds)
            loss = torch.tensor(0.0, device=device)
            total_weight = 0.0
            for i in range(n_iters):
                weight = gamma ** (n_iters - 1 - i)
                loss = loss + weight * nf_preds[i].mean()
                total_weight += weight
            loss = loss / total_weight  # normalize across iterations
            total_loss += loss.item()
            n += 1
    model.train()
    return total_loss / max(n, 1)


def train_searaft_ssd(data_dir, pairs_dir, device, epochs=3, lr=2e-5, batch_size=2,
                      weight_decay=1e-4, gamma=0.85, grad_clip=5.0, grad_accum=1,
                      val_every=200, early_stop_patience=3, min_delta=0.001,
                      resume=False, run_dir=None, log_every=10, use_tb=True, trial=None):
    """Train SEA-RAFT via SSD. Returns best val_loss."""
    print("Starting SEA-RAFT Simple Self-Distillation...", flush=True)

    train_full = SEARAFTSSDDataset(data_dir, pairs_dir, augment=True)
    eval_full = SEARAFTSSDDataset(data_dir, pairs_dir, augment=False)
    if len(train_full) == 0:
        print("No SEA-RAFT training data found!")
        return float('inf')

    train_ds, val_ds, test_ds = _split_dataset(train_full, eval_full)
    print(f"  {len(train_full)} total -> train={len(train_ds)} val={len(val_ds)} test={len(test_ds)}", flush=True)

    loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                        num_workers=2, persistent_workers=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=0)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=0)

    # Load model
    from align.sea_raft.raft import RAFT as SEARAFT
    from align.flow_refine import _download_sea_raft_weights
    print(f"  Loading SEA-RAFT model...", flush=True)
    model = SEARAFT()
    ckpt_path = _download_sea_raft_weights()
    state_dict = torch.load(ckpt_path, map_location="cpu", weights_only=True)
    if any(k.startswith("module.") for k in state_dict):
        state_dict = {k.replace("module.", "", 1): v for k, v in state_dict.items()}
    model.load_state_dict(state_dict, strict=False)
    model = model.to(device)
    model.train()
    print(f"  SEA-RAFT model loaded", flush=True)

    n_params = sum(p.numel() for p in model.parameters())
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs * len(loader))

    # Logger
    logger = None
    if run_dir:
        logger = MetricsLogger(run_dir, "searaft", use_tb=use_tb)
        logger.log_config({
            "lr": lr, "weight_decay": weight_decay, "gamma": gamma,
            "epochs": epochs, "batch_size": batch_size,
            "train_size": len(train_ds), "val_size": len(val_ds), "test_size": len(test_ds),
            "device": str(device), "params": n_params,
        })

    best_val_loss = float('inf')
    patience_counter = 0
    start_epoch = 0
    weights_path = 'align/weights/searaft_ssd.pth'
    ckpt_path = 'align/weights/searaft_ssd_training.pt'

    if resume and os.path.exists(ckpt_path):
        start_epoch, best_val_loss, patience_counter = _load_training_checkpoint(
            ckpt_path, model, optimizer, scheduler, device)
        start_epoch += 1
        print(f"  Resumed from epoch {start_epoch}, best_val={best_val_loss:.5f}", flush=True)

    for epoch in range(start_epoch, epochs):
        total_loss = 0.0
        n_batches = 0
        epoch_t0 = time.time()

        for refs, srcs, flow_gts in loader:
            batch_t0 = time.time()
            refs = refs.to(device)
            srcs = srcs.to(device)
            flow_gts = flow_gts.to(device)

            output = model(refs, srcs, iters=12, flow_gt=flow_gts, test_mode=False)

            nf_preds = output['nf']
            n_iters = len(nf_preds)
            loss = torch.tensor(0.0, device=device)
            total_weight = 0.0
            for i in range(n_iters):
                weight = gamma ** (n_iters - 1 - i)
                loss = loss + weight * nf_preds[i].mean()
                total_weight += weight
            loss = loss / total_weight  # normalize across iterations

            # Scale loss for gradient accumulation
            (loss / grad_accum).backward()

            loss_val = loss.item()
            total_loss += loss_val
            n_batches += 1

            # Step optimizer every grad_accum batches
            if n_batches % grad_accum == 0:
                grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip).item()
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()
            else:
                grad_norm = 0.0
            batch_time = time.time() - batch_t0

            if n_batches % log_every == 0:
                cur_lr = scheduler.get_last_lr()[0]
                mem = _get_mem_mb(device)
                msg = (f"    [{n_batches}/{len(loader)}] loss={loss_val:.5f} "
                       f"grad={grad_norm:.3f} lr={cur_lr:.2e} "
                       f"{batch_time:.2f}s {mem:.0f}MB")
                print(msg, flush=True)

                if logger:
                    logger.log({
                        "type": "batch", "epoch": epoch, "batch": n_batches,
                        "loss": loss_val, "grad_norm": grad_norm,
                        "lr": cur_lr, "batch_time_s": batch_time,
                        "mem_mb": mem,
                    })

            # Intra-epoch val check
            if val_every and n_batches % val_every == 0:
                val_loss = _eval_searaft(model, val_loader, device, gamma)
                improved = val_loss < best_val_loss - min_delta
                if improved:
                    best_val_loss = val_loss
                    patience_counter = 0
                    os.makedirs('align/weights', exist_ok=True)
                    torch.save(model.state_dict(), weights_path)
                    print(f"    VAL [{n_batches}] val={val_loss:.5f} [best, saved]", flush=True)
                else:
                    patience_counter += 1
                    print(f"    VAL [{n_batches}] val={val_loss:.5f} "
                          f"[no improvement {patience_counter}/{early_stop_patience}]", flush=True)

                if logger:
                    logger.log({
                        "type": "val_check", "epoch": epoch, "batch": n_batches,
                        "val_loss": val_loss, "best_val_loss": best_val_loss,
                    })

                if trial is not None:
                    trial.report(val_loss, epoch * len(loader) + n_batches)

                if early_stop_patience and patience_counter >= early_stop_patience:
                    print(f"    Early stopping at epoch {epoch+1} batch {n_batches}", flush=True)
                    break

        if early_stop_patience and patience_counter >= early_stop_patience:
            break

        epoch_time = time.time() - epoch_t0
        avg_loss = total_loss / max(n_batches, 1)

        if not val_every or n_batches % val_every != 0:
            val_loss = _eval_searaft(model, val_loader, device, gamma)
            improved = val_loss < best_val_loss - min_delta
            if improved:
                best_val_loss = val_loss
                patience_counter = 0
                os.makedirs('align/weights', exist_ok=True)
                torch.save(model.state_dict(), weights_path)

        print(f"  Epoch {epoch+1}/{epochs} — train={avg_loss:.5f} val={val_loss:.5f} "
              f"best={best_val_loss:.5f} ({epoch_time:.0f}s)", flush=True)

        if logger:
            logger.log({
                "type": "epoch_summary", "epoch": epoch,
                "train_loss": avg_loss, "val_loss": val_loss,
                "best_val_loss": best_val_loss, "epoch_time_s": epoch_time,
            })

        # Save training checkpoint for resume
        os.makedirs('align/weights', exist_ok=True)
        _save_training_checkpoint(ckpt_path, model, optimizer, scheduler,
                                  epoch, best_val_loss, patience_counter)
        print(f"  Training checkpoint saved (resumable)", flush=True)

    # Reload best weights for test eval
    if os.path.exists(weights_path):
        model.load_state_dict(torch.load(weights_path, map_location=device))

    test_loss = _eval_searaft(model, test_loader, device, gamma)
    print(f"  Test loss: {test_loss:.5f} (best val: {best_val_loss:.5f})", flush=True)
    if logger:
        logger.log({"type": "test", "test_loss": test_loss, "best_val_loss": best_val_loss})
    print(f"  Weights at {weights_path}", flush=True)

    if logger:
        logger.close()

    del model, optimizer
    if "mps" in str(device):
        torch.mps.empty_cache()
    elif "cuda" in str(device):
        torch.cuda.empty_cache()

    return best_val_loss


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Run SSD Fine-tuning")
    parser.add_argument("--data-dir", "-d", type=str, required=True,
                        help="Directory with pseudo-label tensors")
    parser.add_argument("--pairs-dir", "-p", type=str, default=None,
                        help="Directory with image pairs (default: inferred from data-dir)")
    parser.add_argument("--epochs", "-e", type=int, default=3)
    parser.add_argument("--roma-only", action="store_true")
    parser.add_argument("--searaft-only", action="store_true")

    # Hyperparameters
    parser.add_argument("--roma-lr", type=float, default=1e-5)
    parser.add_argument("--roma-weight-decay", type=float, default=1e-4)
    parser.add_argument("--roma-conf-weight", type=float, default=0.5)
    parser.add_argument("--searaft-lr", type=float, default=1e-5)
    parser.add_argument("--searaft-weight-decay", type=float, default=1e-4)
    parser.add_argument("--searaft-gamma", type=float, default=0.85)
    parser.add_argument("--grad-clip", type=float, default=20.0)
    parser.add_argument("--grad-accum", type=int, default=1,
                        help="Gradient accumulation steps (effective batch = batch_size * grad_accum)")
    parser.add_argument("--val-every", type=int, default=200,
                        help="Run val check every N batches (0=epoch-only)")
    parser.add_argument("--early-stop-patience", type=int, default=3,
                        help="Stop if val loss doesn't improve for N checks (0=disable)")
    parser.add_argument("--min-delta", type=float, default=0.001,
                        help="Minimum val loss improvement to count as progress")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from last training checkpoint")

    # Logging
    parser.add_argument("--run-id", type=str, default=None,
                        help="Run identifier (default: timestamp)")
    parser.add_argument("--log-every", type=int, default=10,
                        help="Log metrics every N batches")
    parser.add_argument("--no-tb", action="store_true",
                        help="Disable TensorBoard logging")

    args = parser.parse_args()

    device = get_torch_device()
    print(f"Using device: {device}")

    # Infer pairs dir
    pairs_dir = args.pairs_dir
    if pairs_dir is None:
        pairs_dir = args.data_dir.replace("ssd_labels", "ssd_pairs")
        if not os.path.isdir(pairs_dir):
            pairs_dir = os.path.join(os.path.dirname(args.data_dir), "ssd_pairs")

    if not os.path.isdir(pairs_dir):
        print(f"ERROR: Could not find pairs directory at {pairs_dir}")
        print("Provide it explicitly with --pairs-dir")
        sys.exit(1)

    # Setup run directory
    run_id = args.run_id or datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join("diagnostics", "ssd_train", run_id)
    os.makedirs(run_dir, exist_ok=True)

    print(f"Labels:  {args.data_dir}")
    print(f"Pairs:   {pairs_dir}")
    print(f"Run dir: {run_dir}")
    use_tb = not args.no_tb
    if use_tb and not _tb_available:
        print("  (TensorBoard not installed, JSON-only logging)")

    patience = args.early_stop_patience or None

    if not args.searaft_only:
        train_roma_ssd(
            args.data_dir, pairs_dir, device,
            epochs=args.epochs, lr=args.roma_lr, weight_decay=args.roma_weight_decay,
            conf_weight=args.roma_conf_weight, grad_clip=args.grad_clip,
            grad_accum=args.grad_accum,
            val_every=args.val_every, early_stop_patience=patience,
            min_delta=args.min_delta, resume=args.resume,
            run_dir=run_dir, log_every=args.log_every, use_tb=use_tb,
        )
    if not args.roma_only:
        train_searaft_ssd(
            args.data_dir, pairs_dir, device,
            epochs=args.epochs, lr=args.searaft_lr, weight_decay=args.searaft_weight_decay,
            gamma=args.searaft_gamma, grad_clip=args.grad_clip,
            grad_accum=args.grad_accum,
            val_every=args.val_every, early_stop_patience=patience,
            min_delta=args.min_delta, resume=args.resume,
            run_dir=run_dir, log_every=args.log_every, use_tb=use_tb,
        )

    print(f"\nSSD Fine-Tuning Complete! Metrics at: {run_dir}")


if __name__ == "__main__":
    main()
